on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

name: CI

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          persist-credentials: false

      - name: setup rust
        run: |
            rustup toolchain install nightly --component clippy,rustfmt
            rustup default nightly

      - name: setup just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3

      - name: rust cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2

      - name: check
        run: just check
